kind: Service
apiVersion: v1
metadata:
  name: xero-v1
  namespace: demo
  labels:
    k8s-app: xero-v1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:473110518805:certificate/bd3ece6c-8824-40ad-995b-2bdb3b2e4404"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: xero-v1
  ports:
  - port: 443
    protocol: TCP
    name: https
  - port: 80
    protocol: TCP
    name: http
---
kind: Service
apiVersion: v1
metadata:
  name: memcache-xero
  namespace: demo
spec:
  type: ExternalName
  externalName: goodlord.x44gfy.cfg.euw1.cache.amazonaws.com
